apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loco-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-loco
    kind: SecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: DB-CREDENTIAL
