apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-loco
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-key
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-key
